# PHP project
language: php

# which versions of PHP to build with
php:
- 7.3

# set global environment variables
env:
  global:
    # make PROJECTNAME from vendor/project
    # this strips everything before the last /
    - PROJECTNAME=${TRAVIS_REPO_SLUG##*/}

# make sure we have the latest version of composer
before_install:
- composer self-update

# install dependencies
install:
- composer install

# no phpunit tests (yet)
script: true

# no email notifications
notifications:
  email: false

# before deployment make the zipfile to upload
before_deploy:
 # execute release prepare script
 - sh ./vendor/coldtrick/releases/scripts/travis/before_deploy.sh

# deployment settings
deploy:
  provider: releases
  api_key:
    secure: 4CLhE0w4RXaPH8pHevNrzt4U0Q9AQqw+H911yBkdofSfkUY3PRXRqCiOg/Fyf/QsI1onb4R9dCkz5MluyZK+IoM2rKPaV8NXrdmkZWlcyga8UzBOkrxGcaSfBuqniQaQqXE65M6VZ1muk6NUzD7+/i99Gg6ht8xwjTQPlAbsn04=
  # name of the zip to upload
  file: ${PROJECTNAME}_$TRAVIS_TAG.zip
  skip_cleanup: true
  on:
    # only when a tag is created in GitHub
    tags: true
    all_branches: true

after_deploy:
 # execute release after script
 - sh ./vendor/coldtrick/releases/scripts/travis/after_deploy.sh
